modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "CC BY-NC-SA 4.0"

[[mods]]
modId = "liblib"
version = "${version}"
displayName = "LibLib"
authors = "GCJOJO"
description = '''

'''
#logoFile = ""

[[mixins]]
config = "liblib.mixins.json"

[[dependencies.liblib]]
modId = "neoforge"
mandatory = true
versionRange = "[21.1.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.liblib]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.liblib]]
modId = "architectury"
type = "required"
versionRange = "[13.0.11,)"
ordering = "AFTER"
side = "BOTH"

